[project]
name = "delukit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bhanu Prasanna", email = "bhanu.prasanna2001@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "databricks-sql-connector>=4.5.0",
    "entsoe-py>=0.8.1",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "pydantic>=2.13.5",
    "pyrate-limiter>=4.5.0",
    "requests>=2.34.2",
    "snowflake-connector-python>=4.7.4",
    "tqdm>=4.70.1",
]

[project.scripts]
delukit = "delukit:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::bs4.XMLParsedAsHTMLWarning",
]
